/**
 * GitHub DTO
 * A set of TypeScript interfaces and a zero-dependency mapping function.
 * Maps raw `snake_case` JSON properties to `camelCase` application models explicitly,
 * avoiding heavy third-party transformation libraries to maximize parsing performance
 * and reduce runtime overhead.
 */
export interface GitHubEvent {
    id: string;
    type: string;
    actor: Actor;
    repo: Repo;
    payload: Payload;
    publicEvent: boolean;
    
    /**
     * Kept as a raw string to avoid the CPU and garbage collection overhead
     * of instantiating Date objects during tight loops.
     */
    createdAt: string;
}

export interface Actor {
    id: number;
    login: string;
    url: string;
    avatarUrl: string;
}

export interface Repo {
    id: number;
    name: string;
    url: string;
}

/**
 * Handles the polymorphic nature of GitHub payloads.
 * Uses union types (`string | null`) to define optional fields, ensuring
 * predictable execution paths during high-frequency parsing.
 */
export interface Payload {
    ref: string | null;
    refType: string | null;
    masterBranch: string | null;
    description: string | null;
}

/**
 * Maps the raw parsed JSON object to the strictly typed `GitHubEvent` interface.
 * Performs direct O(1) property access and assignment for optimal performance.
 *
 * @param raw - The raw object generated by `JSON.parse()`
 * @returns A strictly mapped `GitHubEvent` object
 */
export const mapToGitHubEvent = (raw: any): GitHubEvent => {
    return {
        id: raw.id,
        type: raw.type,
        
        // Nested explicit mapping
        actor: {
            id: raw.actor.id,
            login: raw.login,
            url: raw.actor.url,
            avatarUrl: raw.actor.avatar_url, // snake_case to camelCase mapping
        },
        
        repo: {
            id: raw.repo.id,
            name: raw.repo.name,
            url: raw.repo.url,
        },
        
        payload: {
            // Using nullish coalescing for safe fallback
            ref: raw.payload?.ref ?? null,
            refType: raw.payload?.ref_type ?? null,
            masterBranch: raw.payload?.master_branch ?? null,
            description: raw.payload?.description ?? null,
        },
        
        publicEvent: raw.public, // mapping 'public' to 'publicEvent'
        createdAt: raw.created_at, // snake_case to camelCase mapping
    };
};