package com.tez.perflab.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.interop.UIKitViewController
import com.tez.perflab.engines.PlatformMediaPlayer
import kotlinx.cinterop.ExperimentalForeignApi
import platform.AVKit.AVPlayerViewController
import platform.AVFoundation.AVLayerVideoGravityResizeAspect

/**
 * iOS-specific implementation of the native video rendering surface.
 * 
 * This component bridges the shared Compose Multiplatform UI tree to the native
 * AVKit pipeline. It is designed to facilitate hardware-accelerated video decoding 
 * while allowing for high-fidelity performance profiling.
 */
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun NativeVideoPlayer(
    player: PlatformMediaPlayer?,
    modifier: Modifier
) {
    /**
     * Uses [AVPlayerViewController] instead of a headless [AVPlayerLayer].
     * This ensures benchmarking consistency with Android’s 'PlayerView' by including
     * the CPU/RAM overhead generated by native playback controls and interaction overlays
     * in the telemetry data.
     */
    UIKitViewController(
        factory = {
            AVPlayerViewController().apply {
                showsPlaybackControls = true
                videoGravity = AVLayerVideoGravityResizeAspect
            }
        },
        modifier = modifier,
        update = { viewController ->
            /**
             * Safely bridges the active hardware decoding session (AVPlayer) to the
             * native View Controller. Direct reference comparison is used to prevent
             * redundant player re-assignments during Compose recomposition cycles.
             */
            val actualAVPlayer = player?.avPlayer

            if (viewController.player != actualAVPlayer) {
                viewController.player = actualAVPlayer
            }
        }
        // 'properties' parameter removed to satisfy stable UIKitViewController signature constraints.
    )
}